version: '3.8'
services:
  web:
    build: .
    volumes:
      - uploads:/app/data/uploads
      - db:/app/data
    environment:
      - FLASK_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/app/data/uploads
    depends_on:
      - web
volumes:
  uploads:
  db: