services:
  web:
    build: .
    volumes:
      - uploads:/app/data/uploads
      - db:/app/data
    environment:
      - FLASK_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/app/data/uploads
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_certs:/etc/letsencrypt
      - uploads:/app/data/uploads
    depends_on:
      - nginx
volumes:
  uploads:
  db:
  certbot_certs: