services:
  web:
    build: .
    volumes:
      - uploads:/app/data/uploads
      - db:/app/data
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/app/data/uploads
      - certs:/etc/nginx/certs:ro
    depends_on:
      - web
      - certbot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew && nginx -s reload; sleep 12h & wait $${!}; done;'"
volumes:
  uploads:
  db:
  certs:
  certs-data: