version: '3.8'
services:
  web:
    build: .
    volumes:
      - uploads:/app/data/uploads
      - db:/app/data
    environment:
      - FLASK_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Добавляем порт для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/app/data/uploads
      - certbot-certs:/etc/letsencrypt  # Для хранения сертификатов
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - nginx
volumes:
  uploads:
  db:
  certbot-certs:  # Новый том для сертификатов